version: '3'
volumes:
  pgdata:
services:
  python: &python
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    volumes:
      - ./src:/src
    ports:
      - 8000:8000
    command: "python3 manage.py runserver 0.0.0.0:8000"
    depends_on:
      - postgres
      - rabbitmq
      - celery_worker
  postgres:
    image: postgres:11-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'
      POSTGRES_PASS: 'postgres'
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
  rabbitmq:
    image: rabbitmq:3.7.14-alpine

  celery_worker:
    <<: *python
    command: celery -A api worker --loglevel=info
    ports: []
    depends_on:
      - postgres
      - rabbitmq
