# Generated by Django 2.1.7 on 2019-04-17 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_auto_20190410_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following_relation',
            field=models.ManyToManyField(through='models.Subscribers', to='models.User'),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='follower_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whomfollows', to='models.User'),
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whofollows', to='models.User'),
        ),
    ]
